### ISSUE TITLE
Migrations may be run twice

### ISSUE THREAD

**Issue by SergeiPatiakin** [rickbergfalk/postgrator#100]
In a web application with multiple backend nodes, it seems that Postgrator migrations may be run twice under certain conditions. Consider an app with two backend nodes and the following migrations for a Postgres DB:

Migration 001
```
create table t(a int);
```

Migration 002
```
insert into t(a) values (42);
```

Suppose that the app is at migration 001. A new version of the app is pushed and both nodes concurrently run migration 002. Is there anything preventing the value 42 from being inserted into `t` twice?

**Comment by rickbergfalk** [comment]
Hi @SergeiPatiakin! 

There's nothing built into postgrator to prevent that and I think somewhat out of scope for the library. 

An approach you could leverage is to use some sort of locking with something like redis, where the first instance to try to migrate tries to require a lock, otherwise does not proceed.

This sort of thing can get messy however, as the instances not migrating up may expect the database to be a certain way, so they technically probably shouldn't fully "start" until migration is complete. 

You may want to consider migrating the db out of band from application startups. 

For example, perhaps you have 3 instances of your app running at v1. You can shut them down, and then in a separate tool or process, migrate the db to v2. Once successful, you can bring up v2 application instances and shut off v1 instances.

Alternatively, if your database migrations are compatible with v1 instances, you can migrate your schema while v1 instances are up, bring up v2, and cut over to them. This approach works well for things like adding a column, but does not work when data migrations are involved (since v1 instances could create "old" looking data in the new schema after a data migration is run).
