### ISSUE TITLE
It's not clear how "undo" files are suposed to be used

### ISSUE THREAD

**Issue by mrsarm** [rickbergfalk/postgrator#120]
Sorry if the question is too obvious, but at least for me is not clear how "undo" files are handled. There is no method in the API to call the execution of them and they are omitted in a normal execution, so how I can call the execution of a "undo" file?

Moreover, because is not clear how to use "undo" files, neither is clear what they are supposed to achieve when using them, but I guess it is as the name state to _undo_ what the _do_ version do, so if the _do_ version does something like `CREATE INDEX my_index...` the _undo_ version should be something like `DROP INDEX my_index;` (just want to confirm).

If the question is not so silly, would be nice to have an explanation in the README file (so it is also exported to the description in the Npm page in the next release).

**Comment by rickbergfalk** [comment]
Hi @mrsarm - yeah the docs could expand on this a bit. Right now all it mentions is a small blurb under usage

> Action must be either "do" or "undo". Do implements the version, and undo undoes it.

It follows similar patterns of other migration frameworks (which might use "up" and "down" here). Usually the down/undo will try and make the database back to the state it was prior to migration. So if you add a table in do, you drop it in undo. Add a column in do, remove the column in undo.

These "undo" scripts are run if you specify a version to migrate to and its is lower than current version. For example if your database is on version 5, and you say migration to 3, it'll apply 5 undo, then 4 undo. (Realize docs don't really convey this either)

Something to consider and I should probably document - writing undo/down migrations is completely optional. Personally since writing this library I've switched to only writing up/do migrations, and make sure they are backwards compatible with the previous version of the software. If migration fails, I halt deploying the next version of software until migrations can be completed.

**Comment by mrsarm** [comment]
Thanks @rickbergfalk , clear enough !
