### ISSUE TITLE
Js migrations can throw errors when not run

### ISSUE THREAD

**Issue by ChristopherChudzicki** [rickbergfalk/postgrator#124]
We recently ran into a situation with a single database where:
- js migration number N queries `some_table.some_column` as part of its `generateSql` function
- a subsequent migration, say N+1, removes `som_table.some_column`

The migrations ran fine once, but then when re-run subsequently with `migrate()` we encountered the following behavior
1. Postgrator runs `generateSql()` for all migrations, regardless of whether they're be run against the target database

    _ERROR: This step errors since, migration N queries a column that has been removed by migration N + 1_
2. After generating all the migration sql, postgrator runs some subset of those, the ones with migration number bigger than `select max(version) from schemaversion;`

**Workaround:** To circumvent this issue, we made Migration N check schemavsersion itself and abort early if max version > N. 

This behavior seems undesirable to me—migrations below the current version should not throw errors, period. (It hasn't been a big deal for us since we use js migrations very rarely.) But perhaps generating all the SQL regardless of whether they'll be run is a requirement for md5 validation? I'm unsure. 

Is this a bug, or by design?

Thanks for postgrator, it's been great!

**Comment by rickbergfalk** [comment]
Thanks @ChristopherChudzicki! Sorry for delay in getting to this.

The generateSql was added on after the fact, and wasn't really too designed but rather something done that fit the existing patterns.

You bring up a good use case where this doesn't work.

It's been a while since I've looked at this code, but my thinking is: 
* the md5 validation could/should be on the JS file itself, not the result of the script
* The JS migration function should only be run prior to the execution of each migration

I wonder if this change would technically warrant a major-version bump in the semver context 🤔

**Comment by rickbergfalk** [comment]
Making updates to the way JS migrations are handled in v5. It isn't set in stone yet, but here's what I've implemented so far:

- JS migrations do not generate md5 hashes for validation. Hashing on the result of the function is tricky because the result is dynamic an could change over time. Hashing on file contents is also tricky because JS culture and Prettier (I love Prettier) mean the formatting could change ever so slightly. So, basically v5 will skip md5 validation on JS migrations. (I personally don't see it as that big of a loss).
- JS migrations will not run to generate SQL until right before they are about to be applied. That is... once a JS migration is applied to a DB, it won't run (the JS) again, unless the migration is applied to a database that does not have that version applied. This should allow old JS migrations to just kinda sit by the wayside and rot away as probably intended.

v5 should be out within next week or so.

**Comment by ChristopherChudzicki** [comment]
@rickbergfalk Awesome, thanks for these updates!
