### ISSUE TITLE
Unable to give port to mssql driver

### ISSUE THREAD

**Issue by feugy** [rickbergfalk/postgrator#15]
I just discovered that postgrator is always using Microsoft's SQL Server default port when connecting.

It's due to the configuration object given to [mssql](http://patriksimek.github.io/node-mssql/#cfg-general) driver used: it awaits for a `port` property which is [never given](https://github.com/rickbergfalk/postgrator/blob/9ffa027498cdaef6aa9c8d1947faed8d549d1559/lib/create-common-client.js#L101).

I did not find in postgrator documentation/code any way to change the connection port, and I guess it must be provided in the `server` configuration property, right ?

**Comment by rickbergfalk** [comment]
Good catch. Yeah there really should be an option to pass in port (for all the drivers supported). For mssql, the config object supports a port property. https://www.npmjs.com/package/mssql.

I can can work on this sometime next week, otherwise I'd be open to a pull request if anyone wants to take this on :)
