### ISSUE TITLE
Postgrator doesn't work with Azure SQL

### ISSUE THREAD

**Issue by wmeddie** [rickbergfalk/postgrator#3]
Azure SQL has some idiosyncrasies compared to the standard SQL Server that prevent it from working with Postgrator's current implementation. I ran into the following issues:

  1. `postgrator.migrate` never seems to run or fails with a ECONNRESET.
  2. Error creating the `schemaversion` table

For 1 it turns out that you need to add `option: { secure: true }` to the sqlConfig.
For 2 Azure SQL doesn't support tables without a primary key/clustered index so you just have to add one to get it working again.

**Comment by rickbergfalk** [comment]
@wmeddie Azure just needs a clustered primary key, not necessary an identity column right? Would you be okay if I just made the version column the primary key? Since it should be unique anyways?

In retrospect I feel silly for not putting indexes/primary keys on these tables. That's like database 101 stuff and now I've become one of those devs that doesn't respect the database. The query to get the latest version in the database would benefit from it too, or at least an index on the column.

**Comment by wmeddie** [comment]
@rickbergfalk clustering on the version should work too.  It's probably better that way since you need to use the version column anyway.

**Comment by rickbergfalk** [comment]
@wmeddie I've published postgrator 2.1.0 to npm. It should be Azure compatible now. Thanks again!
