### ISSUE TITLE
Proposal: Promises support for javascript migrations

### ISSUE THREAD

**Issue by HorusGoul** [rickbergfalk/postgrator#64]
Hey!

I'm using postgrator on one of my projects and I had the need of creating an asynchronous transaction (the SQL is generated asynchronously) but this module doesn't fully give support for that.

I'm about to add it on a fork and I was wondering about the implementation. I don't have experience working with database migrations and maybe there's a better place for this kind of process but here's my use case:

* We have a table with Roles (`role`), another with all the Permissions (`permission`) available and the one that joins them in a n:m relationship (`role_permission`).
* When adding a new permission, we may need to set the default values to the existing roles, which requires inserting new records on `role_permission`.

Asynchronous migrations would help fixing with this use case, as we can just connect to the database and generate the queries. At the end, we would return a generated string that contains all the SQL instructions needed.

I bet there are more use cases for this feature, so let's see what you guys think about it :smile:

**Comment by rickbergfalk** [comment]
Hi @HorusGoul 

Sorry for the delay in responding to this.

This should be possible using SQL alone, but it can potentially get complicated depending on your database and data model. Foe example, you could write an INSERT INTO ... SELECT statement to pull values from a table and conditionally insert if necessary (https://dba.stackexchange.com/questions/2973/how-to-insert-values-into-a-table-from-a-select-query-in-postgresql)

Otherwise, I can see enhancing the generateSql function to be able to return either a string of SQL or a promise that returns a string, but that seems like generating a SQL string asynchronously might be getting too complex for what is actually needed.

Another approach that could be taken is to pass a database connection reference to a migration script, and have the script use that database connection reference to execute various queries. I've personally used umzug this way on some projects, and it seems really flexible but requires a bit more setup. https://github.com/sequelize/umzug.

**Comment by rickbergfalk** [comment]
Giving this more thought I realized that the dynamic SQL returned by a JavaScript function sort of breaks the checksum logic in place today. The checksum is being generated off of the returned SQL itself, not the JavaScript file content. 

If we take the alternate approach and pass the postgrator database connection reference to a JS function to perform some database operations, there isn't even SQL to get a checksum of. 

I'm personally interested in that latter approach as it could be used as a solution for #16.

In these cases however, how should checksums of a migration be managed? Would changing checksum to be of JavaScript be enough? Or should checksum be ignored for JavaScript migrations all together? (a tool like prettier could change styles/file contents over time).

Open to suggestions if anyone has them :)

**Comment by kurtmilam** [comment]
> In these cases however, how should checksums of a migration be managed?

It would be awesome if this could be figured at the migration level. If that could be managed, I'd suggest leaving the current behavior (checksum of generated SQL) the default, with one option for generating a checksum of the JS and another for ignoring the checksum completely.

I doubt I'd use the last option but the second one would be very handy.

Current use-case: We wanted to introduce an exclusion constraint that had a `WHERE created_at < '${now}'` clause since the constraint would conflict with data already in the production database, otherwise, and we didn't want to remove or alter the existing conflicting records.

**Comment by vasilianeugen** [comment]
Hi, if you need an implementation with Promise<string> as SQL statement you can find it here https://github.com/moredevs-srl/postgrator. I needed it in order to import some initial images to AWS while inserting the initial data.

**Comment by rickbergfalk** [comment]
Support for this is now in v4.1.0. 

Reading through this issue again, I realized the checksum issue is not really addressed at all, so if using async functions where the migration could change over time, you'll likely want to disable checksums on migration
