### ISSUE TITLE
Organize migrations into subdirectories?

### ISSUE THREAD

**Issue by tamethecomplex** [rickbergfalk/postgrator#65]
Hi Rick,

Thanks for this project!  It's nice to have a minimal migration tool as opposed to a complex ORM when it's not needed.

How do you suggest splitting up migrations into subdirectories to avoid individual migration files from getting too large?  Ideally, I would be able to call individual sub-files from one high-level migration file.  I can do this in psql by prefixing a line with "\i" as described [here](https://stackoverflow.com/questions/27941275/how-to-run-postgres-sql-script-from-another-script), but this results in an error when trying to run these scripts using postgrator.

Is there a way to do this using postgrator?

**Comment by rickbergfalk** [comment]
Forgot to mention - generally when I write migrations I go for many small migrations per release, and accept that on a failure, a system will be partially migrated until the remaining migrations are fixed.

Operating this way requires migrations be non-destructive and compatible with existing release though, so this understandably may not always be an option.

For example, perhaps a release involves 5 migration scripts. If script 4 fails, script 4 is rolled back, but scripts 1 - 3 are left applied to the system. We hold off updating our application software since there was a failure during migration, but it is okay since existing software should be compatible with migrations 1 - 3.

**Comment by tamethecomplex** [comment]
Thanks @rickbergfalk , this makes sense.  After thinking about this more, keeping to the current method of having every distinct file with its own unique number and avoiding script references simplifies the process.  Also, I haven't tried, but I'm guessing that since I can use a glob pattern for the path to migration files, I can create subdirectories to add some level of organization to the scripts rather than having them all in a single folder.  Closing this issue as I think the system will work well for me as is.  Thanks for the detailed answer!
