### ISSUE TITLE
Postgrator not handling multi-line comments correctly

### ISSUE THREAD

**Issue by thardy** [rickbergfalk/postgrator#78]
I have all my sql files in a sql folder. I started getting the following error in one of my sql files...
Error: Missing end comment mark '*/'.

I only have one `/* and one */ ` in the entire file. The file is basically just a use statement with a big chunk of sql commented out...
```
use dbName
GO
/*
...
*/
```

It's about 923 lines, and it executes just fine in SQL Enterprise Manager.  It's a perfectly valid comment.
I STILL get
Error: Missing end comment mark '*/'.

Can postgrator not handle "too many" lines in a comment?

**Comment by dkline** [comment]
Does your commented text also have GO statements in it? postgrator may be splitting your comment into multiple batches if it does. (per https://github.com/rickbergfalk/postgrator/pull/14).

**Comment by thardy** [comment]
It does!  Thank you.  That's probably it.

**Comment by thardy** [comment]
I still think this should be fixed, btw.  A chunk of SQL with GO statements in it is still a commented out chunk of SQL and should be completely ignored.

**Comment by rickbergfalk** [comment]
Looking back at the GO support... the way it is implemented if very naive and splits the file looking for the GO string in the file. 

Reading a bit about the GO keyword, it seems it is only supported by certain SQL Server tools, and not usually otherwise supported? 

Should the GO parsing be more intelligent or should the attempt to split on GO be removed completely?

**Comment by thardy** [comment]
I think simpler approach is to promote comment checking above GO splitting.  First, check for comments, then completely ignore anything within those comments - all processing, including GO processing.

**Comment by dkline** [comment]
I'd recommend not using go statements with postgrator. By using go statements to split up the scripts (instead of separate files / transactions / other means) I think we are inviting issues where a script partially runs, and the failure could be in any part of the file since each separate go section will run regardless of errors in previous sections.

Dropping go support would be simpler as there wouldn't be a reason to parse the code at all anymore, let alone adding in more parsing for comments.

The only downside to dropping GO support that I can think of is that it may break existing project code for some people.

**Comment by rickbergfalk** [comment]
GO support will officially be removed in v5. You'll still be able to work around it by implementing workarounds with the new `execQuery` function, but I'd recommend against it, as @dkline has pointed out. GO could leave you with partially implemented migrations and that sounds like it'd cause a headache.

If you really need to use the GO keyword, I'd recommend looking at a different solution.
