### ISSUE TITLE
Support for include path statement

### ISSUE THREAD

**Issue by bas080** [rickbergfalk/postgrator#80]
This would make views so much nicer to update.

```sql
ALTER TABLE pony
ADD COLUMN name VARCHAR(64),
ADD COLUMN description VARCHAR(255),
ADD COLUMN image_url VARCHAR(512);

#include "../../src/db/view/pony_view.sql
```
Postgrator complains about the hashtag not being valid SQL

`error: syntax error at or near "#"`

**Comment by dkline** [comment]
Just a side note really, but having references to the current version of objects in external files can cause the original scripts to break and throw errors. This may or may not be an issue depending on your processes e.g., in the below example if someone tries to run all the scripts on a new server, the first script will fail since the view expects a column 'image_url' that doesn't exist yet.

Script 1:
```
ALTER TABLE pony
ADD COLUMN name VARCHAR(64),
ADD COLUMN description VARCHAR(255)
#include "../../src/db/view/pony_view.sql
```
Script 2:
```
ALTER TABLE pony
ADD COLUMN image_url VARCHAR(512)
#include "../../src/db/view/pony_view.sql
```

**Comment by bas080** [comment]
@dkline, You are correct. I'll have to rethink this approach. Thank you.
