### ISSUE TITLE
How to fix/proceed after an md5 conflict has been detected?

### ISSUE THREAD

**Issue by tahmidsadik** [rickbergfalk/postgrator#87]
`Prior to applying migrations to a database, for any existing migration in the migration directory already run Postgrator will validate the md5 checksum to ensure the contents of the script have not changed. If a change is detected, migration will stop reporting an error.`

Is there a way to update the `md5` of that migration script? If not how should one proceed to fix this error.

**Comment by rickbergfalk** [comment]
Not through postgrator there isn't. I think ideally you'd restore the original script, or otherwise update the md5 stored in the database table to match the new script. 

If you are willing to change the md5, you may want to turn the checksum validation off:

```js
const postgrator = new Postgrator({
  validateChecksums: false
})
```

I don't use postgrator much anymore, but I personally lean towards turning the validation off as it seems too strict at times. In some cases I've hit bugs where migrations may run fine in dev environments, but fail when they hit prod because of high db use, deadlocks, etc. Those cases usually require changing the migration, and that causes problems for any environment that already has run the script.

If anyone has any ideas on how to handle this better I'm open to ideas and pull requests! Maybe there's a way to flag a particular migration to ignore the checksum or something?

**Comment by mugli** [comment]
This is what flyway does: https://flywaydb.org/documentation/commandline/repair

If there is any failed migration due to checksum mismatch, you can run `flyway repair` and it'll take the current hash of the file and update it in the database.
