### ISSUE TITLE
Support injecting the db connection

### ISSUE THREAD

**Issue by dodtsair** [rickbergfalk/postgrator#90]
Have you considered changing the signatures to support passing in the db connection?

The current documentation shows this example code:

```
const Postgrator = require('postgrator')

const postgrator = new Postgrator({
  // Directory containing migration files
  migrationDirectory: __dirname + '/migrations',
  // or a glob pattern to files
  migrationPattern: __dirname + '/some/pattern/*',
  // Driver: must be pg, mysql, mysql2 or mssql
  driver: 'pg',
  // Database connection config
  host: '127.0.0.1',
  port: 5432,
  database: 'databasename',
  username: 'username',
  password: 'password',
  // Schema table name. Optional. Default is schemaversion
  // If using Postgres, schema may be specified using . separator
  // For example, { schemaTable: 'schema_name.table_name' }
  schemaTable: 'schemaversion'
})

```

In this case the driver, host, port, database, username, password are all given to postgrator to do the migration.  Postgrator then must create the db connection in order to connect to the database.  

But there are reasons to initialize the database connection and pass that to postgrator which would look something like:

```
const pg = require('pg);
const pgInitialized = require('pg-initializer).initialize(pg);
const Postgrator = require('postgrator')

const postgrator = new Postgrator({
  // Directory containing migration files
  migrationDirectory: __dirname + '/migrations',
  // or a glob pattern to files
  migrationPattern: __dirname + '/some/pattern/*',
  // Driver: must be pg, mysql, mysql2 or mssql
  connection: pgInitialized,
  schemaTable: 'schemaversion'
})
```

**Comment by rickbergfalk** [comment]
I have thought about it somewhat... It is certainly an approach that could be taken. I'd be open to a PR if someone wants to take the work on. 

I'm not using postgrator at all anymore so it'll be a low priority for me personally.

It'd definitely make the configuration more flexible and would remove the need to map config to things internally.

**Comment by rickbergfalk** [comment]
Another approach would be to do something like umzug https://www.npmjs.com/package/umzug

**Comment by rflprr** [comment]
@rickbergfalk Just curious, if not postgrator, what do you use now for your migrations?

**Comment by rickbergfalk** [comment]
I'm only maintaining 2 projects at the moment and both use umzug. Not because I think it is a better library necessarily, but a better fit for the projects.

One project heavily used Sequelize so we decided on using umzug for migrations since it had integrations for Sequelize already included. 

For [SQLPad](https://github.com/rickbergfalk/sqlpad), I'm in the process of migrating an nedb database (an embedded db similar to mongodb) to SQLite, and want to leverage the Sequelize/umzug "queryInterface" for writing the migrations, which in theory should allow me to also support another database later on if that project continues to grow. 

The ability to potentially switch from SQLite to Postgres is the only reason I'm entertaining Sequelize/Umzug though. I otherwise recommend _not_ using Sequelize and trying something like [Prisma](https://www.prisma.io/) instead (its migrations are experimental though).

Now that I write this though... I'm kind of questioning whether I shouldn't be adding SQLite support to Postgrator, and using Prisma for query building, and then deal with supporting another db like Postgres if that time comes 😅

**Comment by rickbergfalk** [comment]
I added support for this in 4.3, and in upcoming v5 injecting the connection is going to be the only option allowed.

To use this functionality you need to provide an `execQuery` function that returns an expected format. I'll be writing up a more detailed guide once I get v5 wrapped up.

Not only will this be the most flexible, it'll also save me from having to update for various configs/driver updates.
